// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"github.com/Goboolean/manager-cli/internal/adaptor/backup-meta"
	"github.com/Goboolean/manager-cli/internal/adaptor/command"
	"github.com/Goboolean/manager-cli/internal/adaptor/file"
	"github.com/Goboolean/manager-cli/internal/adaptor/product-meta-repo"
	"github.com/Goboolean/manager-cli/internal/adaptor/status"
	"github.com/Goboolean/manager-cli/internal/adaptor/trade-repo-dump"
	"github.com/Goboolean/manager-cli/internal/adaptor/transaction-manager/transaction-creator"
	"github.com/Goboolean/manager-cli/internal/adaptor/transmission/mock"
	"github.com/Goboolean/manager-cli/internal/domain/service/backup"
	"github.com/Goboolean/manager-cli/internal/domain/service/registration"
	status2 "github.com/Goboolean/manager-cli/internal/domain/service/status"
	"github.com/Goboolean/manager-cli/internal/infrastructure/file"
	"github.com/Goboolean/manager-cli/internal/infrastructure/grpc/props"
	"github.com/Goboolean/manager-cli/internal/infrastructure/rdbms"
	"github.com/Goboolean/manager-cli/internal/port/in"
	"github.com/Goboolean/manager-cli/internal/port/out"
	"github.com/Goboolean/shared/pkg/mongo"
	"github.com/Goboolean/shared/pkg/resolver"
	"github.com/google/wire"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"os"
)

// Injectors from wire.go:

func InitCommandAdaptor() (*command.CommandAdaptor, error) {
	psql, err := provideRdbmsInfra()
	if err != nil {
		return nil, err
	}
	db, err := provideMongoInfra()
	if err != nil {
		return nil, err
	}
	transactionFactory := transactionCreator.New(psql, db)
	tradeDumpAdaptor, err := provideTradeRepoDumpAdaptor()
	if err != nil {
		return nil, err
	}
	metadataRepositoryAdaptor := productMetaRepo.New(psql)
	transmissionAdaptorMock := transmissionMock.New()
	fileInfra := fileInf.New()
	fileAdaptor := file.New(fileInfra)
	backupMetaAdaptor := backupMeta.New(fileInfra)
	string2 := getBackupOutDir()
	backupService := backup.New(transactionFactory, tradeDumpAdaptor, metadataRepositoryAdaptor, transmissionAdaptorMock, fileAdaptor, backupMetaAdaptor, string2)
	registrationService := registration.New(transactionFactory, metadataRepositoryAdaptor)
	stockConfiguratorClient, err := provideGrpcInfra()
	if err != nil {
		return nil, err
	}
	statusAdaptor := status.New(stockConfiguratorClient)
	statusService := status2.New(statusAdaptor)
	commandAdaptor := command.New(backupService, registrationService, statusService)
	return commandAdaptor, nil
}

// wire.go:

// TODO: separate get argus funcs to other struct or package
func getBackupOutDir() string {
	return os.Getenv("BACKUP_OUT_DIR")
}

func getMongoArgs() *resolver.ConfigMap {
	return &resolver.ConfigMap{
		"HOST":     os.Getenv("MONGO_HOST"),
		"USER":     os.Getenv("MONGO_USER"),
		"PORT":     os.Getenv("MONGO_PORT"),
		"PASSWORD": os.Getenv("MONGO_PASS"),
		"DATABASE": os.Getenv("MONGO_DATABASE"),
	}
}

func getPsqlArgs() *resolver.ConfigMap {
	return &resolver.ConfigMap{
		"HOST":     os.Getenv("PSQL_HOST"),
		"USER":     os.Getenv("PSQL_USER"),
		"PORT":     os.Getenv("PSQL_PORT"),
		"PASSWORD": os.Getenv("PSQL_PASS"),
		"DATABASE": os.Getenv("PSQL_DATABASE"),
	}
}

func getGrpcArgs() *resolver.ConfigMap {
	return &resolver.ConfigMap{
		"HOST": os.Getenv("STATUSAPI_HOST"),
		"PORT": os.Getenv("STATUSAPI_PORT"),
	}
}

func getBuycycleArgs() *resolver.ConfigMap {
	return &resolver.ConfigMap{
		"HOST": os.Getenv("BUYCYCLE_HOST"),
		"PORT": os.Getenv("BUYCYCLE_PORT"),
	}
}

func getPolygonArgs() *resolver.ConfigMap {
	return &resolver.ConfigMap{
		"KEY": os.Getenv("POLYGON_API_KEY"),
	}
}

func getPrometheusArgs() *resolver.ConfigMap {
	return &resolver.ConfigMap{
		"PORT": os.Getenv("METRIC_PORT"),
	}
}

func provideGrpcInfra() (grpcapi.StockConfiguratorClient, error) {

	c := getGrpcArgs()

	host, err := c.GetStringKey("HOST")
	if err != nil {
		return nil, err
	}

	port, err := c.GetStringKey("PORT")
	if err != nil {
		return nil, err
	}

	conn, err := grpc.Dial(host+":"+port, grpc.WithTransportCredentials(insecure.NewCredentials()))

	if err != nil {
		return nil, err
	}

	return grpcapi.NewStockConfiguratorClient(conn), nil
}

func provideMongoInfra() (*mongo.DB, error) {
	c := getMongoArgs()

	return mongo.NewDB(c)
}

func provideRdbmsInfra() (*rdbms.PSQL, error) {
	c := getPsqlArgs()

	return rdbms.NewDB(c)
}

var InfraSet = wire.NewSet(fileInf.New, provideGrpcInfra,
	provideMongoInfra,
	provideRdbmsInfra,
)

func provideTradeRepoDumpAdaptor() (*tradeRepoDump.TradeDumpAdaptor, error) {
	c := getMongoArgs()
	return tradeRepoDump.New(c)
}

var AdaptorSet = wire.NewSet(backupMeta.New, command.New, file.New, productMetaRepo.New, status.New, provideTradeRepoDumpAdaptor, transactionCreator.New, transmissionMock.New, wire.Bind(new(out.BackupMetaPort), new(*backupMeta.BackupMetaAdaptor)), wire.Bind(new(out.DataTransmitterPort), new(*transmissionMock.TransmissionAdaptorMock)), wire.Bind(new(out.FileOperatorPort), new(*file.FileAdaptor)), wire.Bind(new(out.MetadataRepositoryPort), new(*productMetaRepo.MetadataRepositoryAdaptor)), wire.Bind(new(out.StatusPort), new(*status.StatusAdaptor)), wire.Bind(new(out.TradeDumperPort), new(*tradeRepoDump.TradeDumpAdaptor)), wire.Bind(new(out.TransactionCreator), new(*transactionCreator.TransactionFactory)))

var ServiceSet = wire.NewSet(backup.New, registration.New, status2.New, getBackupOutDir, wire.Bind(new(in.BackupCmdPort), new(*backup.BackupService)), wire.Bind(new(in.RegCmdPort), new(*registration.RegistrationService)), wire.Bind(new(in.StatusCmdPort), new(*status2.StatusService)))
