// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: queries.sql

package rdbms

import (
	"context"
	"database/sql"
)

const checkProductIsStored = `-- name: CheckProductIsStored :one
SELECT EXISTS(SELECT 1 FROM store_log WHERE product_id  = ($1))
`

func (q *Queries) CheckProductIsStored(ctx context.Context, productID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProductIsStored, productID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deletePlatformInfo = `-- name: DeletePlatformInfo :exec
DELETE FROM product_platform WHERE product_id = ($1) AND platform_name = ($2)
`

type DeletePlatformInfoParams struct {
	ProductID    string
	PlatformName string
}

func (q *Queries) DeletePlatformInfo(ctx context.Context, arg DeletePlatformInfoParams) error {
	_, err := q.db.ExecContext(ctx, deletePlatformInfo, arg.ProductID, arg.PlatformName)
	return err
}

const getProductIdBySymbol = `-- name: GetProductIdBySymbol :one
SELECT id FROM product_meta WHERE symbol = ($1)
`

func (q *Queries) GetProductIdBySymbol(ctx context.Context, symbol string) (string, error) {
	row := q.db.QueryRowContext(ctx, getProductIdBySymbol, symbol)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getProductMeta = `-- name: GetProductMeta :one
SELECT id, "name", symbol, "description", "type", exchange,  "location"  FROM product_meta WHERE id = ($1)
`

func (q *Queries) GetProductMeta(ctx context.Context, id string) (ProductMetum, error) {
	row := q.db.QueryRowContext(ctx, getProductMeta, id)
	var i ProductMetum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Symbol,
		&i.Description,
		&i.Type,
		&i.Exchange,
		&i.Location,
	)
	return i, err
}

const getProductMetaWithPlatform = `-- name: GetProductMetaWithPlatform :one
SELECT product_meta.id, "name", symbol, "description", "type", exchange,  "location" , platform_name, identifier 
FROM product_meta 
JOIN product_platform 
ON product_meta.id = product_platform.product_id 
WHERE product_meta.id = ($1)
`

type GetProductMetaWithPlatformRow struct {
	ID           string
	Name         string
	Symbol       string
	Description  sql.NullString
	Type         string
	Exchange     string
	Location     sql.NullString
	PlatformName string
	Identifier   string
}

func (q *Queries) GetProductMetaWithPlatform(ctx context.Context, id string) (GetProductMetaWithPlatformRow, error) {
	row := q.db.QueryRowContext(ctx, getProductMetaWithPlatform, id)
	var i GetProductMetaWithPlatformRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Symbol,
		&i.Description,
		&i.Type,
		&i.Exchange,
		&i.Location,
		&i.PlatformName,
		&i.Identifier,
	)
	return i, err
}

const getStoredProductList = `-- name: GetStoredProductList :many
SELECT id FROM product_meta,store_log WHERE product_meta.id = store_log.product_id
`

func (q *Queries) GetStoredProductList(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getStoredProductList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNewProductMeta = `-- name: InsertNewProductMeta :exec
INSERT INTO product_meta (id, "name", symbol, "description", "type", exchange, "location") 
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertNewProductMetaParams struct {
	ID          string
	Name        string
	Symbol      string
	Description sql.NullString
	Type        string
	Exchange    string
	Location    sql.NullString
}

func (q *Queries) InsertNewProductMeta(ctx context.Context, arg InsertNewProductMetaParams) error {
	_, err := q.db.ExecContext(ctx, insertNewProductMeta,
		arg.ID,
		arg.Name,
		arg.Symbol,
		arg.Description,
		arg.Type,
		arg.Exchange,
		arg.Location,
	)
	return err
}

const insertNewProductPlatformMeta = `-- name: InsertNewProductPlatformMeta :exec
INSERT INTO product_platform (product_id, platform_name, identifier)
VALUES ($1, $2, $3)
`

type InsertNewProductPlatformMetaParams struct {
	ProductID    string
	PlatformName string
	Identifier   string
}

func (q *Queries) InsertNewProductPlatformMeta(ctx context.Context, arg InsertNewProductPlatformMetaParams) error {
	_, err := q.db.ExecContext(ctx, insertNewProductPlatformMeta, arg.ProductID, arg.PlatformName, arg.Identifier)
	return err
}

const insertPlatformInfo = `-- name: InsertPlatformInfo :exec
INSERT INTO product_platform (product_id, platform_name, identifier) VALUES ($1, $2, $3)
`

type InsertPlatformInfoParams struct {
	ProductID    string
	PlatformName string
	Identifier   string
}

func (q *Queries) InsertPlatformInfo(ctx context.Context, arg InsertPlatformInfoParams) error {
	_, err := q.db.ExecContext(ctx, insertPlatformInfo, arg.ProductID, arg.PlatformName, arg.Identifier)
	return err
}

const updatePlatformIdentifier = `-- name: UpdatePlatformIdentifier :exec
UPDATE product_platform SET identifier = ($1) WHERE product_id = ($2) AND platform_name = ($3)
`

type UpdatePlatformIdentifierParams struct {
	Identifier   string
	ProductID    string
	PlatformName string
}

func (q *Queries) UpdatePlatformIdentifier(ctx context.Context, arg UpdatePlatformIdentifierParams) error {
	_, err := q.db.ExecContext(ctx, updatePlatformIdentifier, arg.Identifier, arg.ProductID, arg.PlatformName)
	return err
}
